[tidb_servers]
10.0.1.39

[tikv_servers]
10.0.1.193
10.0.1.204
10.0.1.201

[pd_servers]
10.0.1.105

[monitoring_servers]
10.0.1.105

[monitored_servers:children]
tidb_servers
tikv_servers
pd_servers

[all:vars]
# ssh via root:
# ansible_user = root
# ansible_become = true
# ansible_become_user = tidb

# ssh via normal user
ansible_user = ubuntu
