---
# Copyright 2016 PingCAP, Inc.

# The playbook of TiDB


- hosts: pd_servers
  tasks:
  - name: stop PD
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh;
    with_items:
    - pd

- hosts: tikv_servers
  tasks:
  - name: stop TiKV
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh; 
    with_items:
    - tikv


- hosts: tidb_servers
  tasks:
  - name: stop TiDB
    shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh; 
    with_items:
    - tidb

    
