---

- hosts: default
  become: yes
  tasks:
    - name: Using aliyun mirror
      copy:
        src=aliyun-ubuntu-sources.list
        dest=/etc/apt/sources.list

    - name: Upgrade system
      apt: update_cache=yes upgrade=yes

    - name: Install essential packages
      apt:
        name='{{ item }}'
        state=present
        install_recommends=no
        update_cache=yes
      with_items:
        - ntp
        - openssl
        - curl
        - wget
        - tar
        - zip
        - unzip
        - git
        - socat
        - python-pip
        - python-yaml
        - mysql-client
        - mydumper
        - build-essential
        - sysbench
        - systemtap

    - name: Install perf
      shell: ls /boot | awk -F- '/vmlinuz/{print $2"-"$3}' | sudo xargs -i apt-get install -y linux-tools-{}-generic

    - name: Ensure ntpd service enabled
      service: name=ntp enabled=yes

    - name: Set timezone
      timezone: name=Asia/Shanghai

    - name: Install awscli
      pip: name=awscli

    - name: Add ansible ppa
      apt_repository:
        repo: 'ppa:ansible/ansible'

    - name: Install ansible
      apt:
        name=ansible
        state=latest
        update_cache=yes
        install_recommends=no

    - name: Add dockerproject key
      apt_key:
        keyserver=hkp://p80.pool.sks-keyservers.net:80
        id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Add dockerproject repo for ubuntu
      apt_repository:
        repo='deb https://mirrors.tuna.tsinghua.edu.cn/docker/apt/repo ubuntu-trusty main'
        state=present

    - name: Install docker
      apt:
        name=docker-engine
        state=latest
        install_recommends=no
        update_cache=yes

    - name: Get FlameGraph
      unarchive:
        src=https://github.com/brendangregg/FlameGraph/archive/master.zip
        dest=/opt
        remote_src=yes
        mode=0755
